GSTREAMER_PLUGINS_CORE := coreelements coreindexers adder app audioconvert audiorate audioresample audiotestsrc ffmpegcolorspace gdp gio pango typefindfunctions videorate videoscale videotestsrc volume autodetect videofilter
GSTREAMER_PLUGINS_CAPTURE := camerabin2
GSTREAMER_PLUGINS_CODECS_RESTRICTED := asfmux dtsdec faad mpegdemux2 mpegpsmux mpegtsdemux mpegtsmux a52dec amrnb amrwbdec asf mad mpeg2dec mpegaudioparse realmedia ffmpeg
GSTREAMER_PLUGINS_ENCODING := encoding
GSTREAMER_PLUGINS_DVD := indvd dvdlpcmdec dvdread
GSTREAMER_PLUGINS_CODECS_GPL := assrender
GSTREAMER_PLUGINS_NET_RESTRICTED := mms
GSTREAMER_PLUGINS_SYS := eglglessink opensles
GSTREAMER_PLUGINS_VIS := libvisual goom goom2k1 audiovisualizers
GSTREAMER_PLUGINS_PLAYBACK := uridecodebin playback
GSTREAMER_PLUGINS_EFFECTS := alpha alphacolor audiofx cairo cutter debug deinterlace effectv equalizer gdkpixbuf imagefreeze interleave level multifile replaygain shapewipe smpte spectrum videobox videocrop videomixer autoconvert bayer coloreffects faceoverlay fieldanalysis freeverb frei0r gaudieffects geometrictransform interlace jp2kdecimator liveadder rawparse removesilence scaletempo segmentclip smooth soundtouch speed stereo videofiltersbad videomeasure videosignal
GSTREAMER_PLUGINS_CODECS := subparse ogg theora vorbis ivorbisdec alaw annodex apetag audioparsers auparse avi dv flac flv flxdec icydemux id3demux isomp4 jpeg matroska mulaw multipart png speex taglib wavenc wavpack wavparse y4menc adpcmdec adpcmenc aiff cdxaparse dtmf dvbsuboverlay dvdspu fragmented hdvparse id3tag ivfparse jp2k kate mve mxf nsf nuvdemux opus pcapparse pnm schro gstsiren subenc tta videoparsersbad vmnc vp8 y4mdec androidmedia
GSTREAMER_PLUGINS_NET := tcp rtsp rtp gstrtpmanager soup udp dataurisrc rtpmux rtpvp8 sdp
